'use client';

import { useEffect, useState } from 'react';
import { Activity, AlertTriangle, CheckCircle2, Clock3, ListTodo, RefreshCw, Workflow } from 'lucide-react';
import { supabase } from '@/lib/supabase';

type Task = { id:string; title:string; task_type:string; priority:string; status:string; due_at:string|null; workflow_id:string|null; asset_id:string|null };
type Exception = { id:string; title:string; severity:string; status:string; reason:string|null; created_at:string; asset_id:string|null };
type WorkflowRow = { id:string; name:string; workflow_type:string; owner_role:string; status:string; sla_hours:number };

export function Phase13OperationsWorkspace() {
 const [tasks,setTasks]=useState<Task[]>([]); const [exceptions,setExceptions]=useState<Exception[]>([]); const [workflows,setWorkflows]=useState<WorkflowRow[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null);
 async function load(){
  setLoading(true); setError(null);
  const {data:{user}}=await supabase.auth.getUser(); if(!user){setError('Sign in required');setLoading(false);return;}
  const {data:profile}=await supabase.from('profiles').select('organization_id').eq('id',user.id).maybeSingle(); if(!profile?.organization_id){setError('No organization is assigned to this account');setLoading(false);return;}
  const [t,e,w]=await Promise.all([
   supabase.from('operational_tasks').select('id,title,task_type,priority,status,due_at,workflow_id,asset_id').eq('organization_id',profile.organization_id).order('due_at',{ascending:true,nullsFirst:false}).limit(30),
   supabase.from('operational_exceptions').select('id,title,severity,status,reason,created_at,asset_id').eq('organization_id',profile.organization_id).order('created_at',{ascending:false}).limit(20),
   supabase.from('operational_workflows').select('id,name,workflow_type,owner_role,status,sla_hours').eq('organization_id',profile.organization_id).order('created_at',{ascending:false})
  ]);
  const firstError=t.error||e.error||w.error; if(firstError)setError(firstError.message); else {setTasks((t.data||[]) as Task[]);setExceptions((e.data||[]) as Exception[]);setWorkflows((w.data||[]) as WorkflowRow[]);} setLoading(false);
 }
 useEffect(()=>{load()},[]);
 async function setTaskStatus(task:Task,status:string){ const {error:e}=await supabase.from('operational_tasks').update({status,completed_at:status==='COMPLETED'?new Date().toISOString():null,updated_at:new Date().toISOString()}).eq('id',task.id); if(e)setError(e.message); else load(); }
 async function setExceptionStatus(item:Exception,status:string){ const {error:e}=await supabase.from('operational_exceptions').update({status,resolved_at:status==='RESOLVED'||status==='WAIVED'?new Date().toISOString():null,updated_at:new Date().toISOString()}).eq('id',item.id); if(e)setError(e.message); else load(); }
 const open=tasks.filter(t=>t.status==='OPEN'||t.status==='IN_PROGRESS'||t.status==='BLOCKED').length, critical=exceptions.filter(e=>e.severity==='CRITICAL'&&e.status==='OPEN').length, overdue=tasks.filter(t=>t.due_at&&new Date(t.due_at).getTime()<Date.now()&&!['COMPLETED','CANCELLED'].includes(t.status)).length;
 return <main className="mx-auto max-w-[1540px] space-y-6 p-4 md:p-8">
  <section className="assetflow-command rounded-3xl p-6 md:p-8"><div className="relative z-10"><div className="mb-3 flex flex-wrap items-center gap-2"><span className="assetflow-eyebrow">Phase 13 · Institutional Operations</span><span className="assetflow-status"><span className="assetflow-live-dot"/> Workflow control online</span></div><h1 className="font-display text-3xl font-semibold tracking-[-.04em] text-white md:text-5xl">Turn institutional events into accountable work.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-400">Operational queues, ownership, SLAs and exception handling across onboarding, settlement, servicing, compliance and review.</p></div></section>
  <div className="grid grid-cols-2 gap-3 md:grid-cols-4"><K label="Open work" value={String(open)} icon={ListTodo}/><K label="Overdue" value={String(overdue)} icon={Clock3}/><K label="Critical exceptions" value={String(critical)} icon={AlertTriangle}/><K label="Active workflows" value={String(workflows.filter(w=>w.status==='ACTIVE').length)} icon={Workflow}/></div>
  {error&&<div className="rounded-2xl border border-rose-400/20 bg-rose-400/5 p-4 text-sm text-rose-200">{error}</div>}
  <div className="grid gap-6 xl:grid-cols-[1.4fr_.8fr]">
   <Panel title="Operational queue" icon={ListTodo} action={<button onClick={load} className="rounded-lg p-2 text-slate-500 hover:bg-white/5 hover:text-white"><RefreshCw className="h-4 w-4"/></button>}><div className="space-y-2">{!loading&&!tasks.length&&<Empty text="No operational work has been created yet."/>}{tasks.map(t=><div key={t.id} className="flex flex-col gap-3 rounded-xl border border-white/[.06] bg-white/[.02] p-4 md:flex-row md:items-center md:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full border border-white/10 px-2 py-1 font-mono text-[9px] text-slate-500">{t.priority}</span><span className="font-mono text-[9px] text-cyan-300">{t.task_type}</span></div><p className="mt-2 text-sm font-medium text-slate-200">{t.title}</p><p className="mt-1 font-mono text-[10px] text-slate-600">{t.due_at?`SLA ${new Date(t.due_at).toLocaleString()}`:'No due date'} · {t.status}</p></div><div className="flex gap-2">{t.status!=='IN_PROGRESS'&&t.status!=='COMPLETED'&&<button onClick={()=>setTaskStatus(t,'IN_PROGRESS')} className="rounded-lg border border-white/10 px-3 py-2 text-[10px] text-slate-300 hover:bg-white/5">Start</button>}{t.status!=='COMPLETED'&&<button onClick={()=>setTaskStatus(t,'COMPLETED')} className="rounded-lg border border-emerald-400/20 px-3 py-2 text-[10px] text-emerald-300 hover:bg-emerald-400/5">Complete</button>}</div></div>)}</div></Panel>
   <Panel title="Workflow catalog" icon={Workflow}><div className="space-y-2">{!loading&&!workflows.length&&<Empty text="No workflows configured yet."/>}{workflows.map(w=><div key={w.id} className="rounded-xl border border-white/[.06] bg-white/[.02] p-3"><div className="flex items-center justify-between"><p className="text-sm font-medium text-slate-200">{w.name}</p><span className="text-[9px] text-emerald-300">{w.status}</span></div><p className="mt-1 font-mono text-[10px] text-slate-600">{w.workflow_type} · owner {w.owner_role} · SLA {w.sla_hours}h</p></div>)}</div></Panel>
  </div>
  <Panel title="Exception control" icon={AlertTriangle} action={<span className="font-mono text-[9px] text-slate-600">OPEN / ACKNOWLEDGED / RESOLVED</span>}><div className="overflow-x-auto"><table className="w-full text-left"><thead><tr className="border-b border-white/[.06] text-[9px] uppercase tracking-[.16em] text-slate-600"><th className="py-3">Exception</th><th>Severity</th><th>Status</th><th>Created</th><th/></tr></thead><tbody>{exceptions.map(e=><tr key={e.id} className="border-b border-white/[.04] text-xs text-slate-400"><td className="py-3"><p className="text-slate-200">{e.title}</p><p className="mt-1 text-[10px] text-slate-600">{e.reason||'No reason recorded'}</p></td><td className={e.severity==='CRITICAL'?'text-rose-300':e.severity==='WATCH'?'text-amber-300':'text-slate-400'}>{e.severity}</td><td>{e.status}</td><td className="font-mono text-[10px]">{new Date(e.created_at).toLocaleString()}</td><td className="text-right">{e.status==='OPEN'&&<button onClick={()=>setExceptionStatus(e,'ACKNOWLEDGED')} className="rounded-lg border border-white/10 px-2 py-1 text-[9px] hover:bg-white/5">Acknowledge</button>}{e.status==='ACKNOWLEDGED'&&<button onClick={()=>setExceptionStatus(e,'RESOLVED')} className="rounded-lg border border-emerald-400/20 px-2 py-1 text-[9px] text-emerald-300 hover:bg-emerald-400/5">Resolve</button>}</td></tr>)}</tbody></table>{!loading&&!exceptions.length&&<Empty text="No operational exceptions recorded."/>}</div></Panel>
  <div className="flex items-center gap-2 text-xs text-slate-600"><Activity className="h-4 w-4"/> Phase 13 establishes the control plane for turning upstream asset, compliance and settlement events into owned operational outcomes.</div>
 </main>
}
function K({label,value,icon:Icon}:{label:string;value:string;icon:any}){return <div className="assetflow-kpi"><p>{label}</p><strong>{value}</strong><span><Icon className="mr-1 inline h-3 w-3"/> organization scoped</span></div>}
function Panel({title,icon:Icon,action,children}:{title:string;icon:any;action?:React.ReactNode;children:React.ReactNode}){return <section className="assetflow-panel rounded-2xl p-5"><div className="mb-4 flex items-center justify-between"><h2 className="flex items-center gap-2 font-display text-sm font-semibold text-white"><Icon className="h-4 w-4 text-cyan-300"/>{title}</h2>{action}</div>{children}</section>}
function Empty({text}:{text:string}){return <div className="py-8 text-center text-xs text-slate-600">{text}</div>}
