'use client';

import { useEffect, useState } from 'react';
import { Zap, GitBranch, Activity, ShieldAlert, Plus, RefreshCw } from 'lucide-react';
import { supabase } from '@/lib/supabase';

type Rule={id:string;name:string;source_domain:string;event_type:string;target_workflow_type:string;enabled:boolean;auto_assign_role:string|null;priority:string;sla_hours:number};
type Trigger={id:string;source_domain:string;event_type:string;status:string;idempotency_key:string;created_at:string;workflow_id:string|null;task_id:string|null};

export function Phase14OrchestrationWorkspace(){
 const [rules,setRules]=useState<Rule[]>([]); const [triggers,setTriggers]=useState<Trigger[]>([]); const [org,setOrg]=useState<string|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null);
 async function load(){setLoading(true);setError(null);const {data:{user}}=await supabase.auth.getUser();if(!user){setError('Sign in required');setLoading(false);return;}const {data:p}=await supabase.from('profiles').select('organization_id').eq('id',user.id).maybeSingle();if(!p?.organization_id){setError('No organization is assigned to this account');setLoading(false);return;}setOrg(p.organization_id);const [r,t]=await Promise.all([supabase.from('event_rules').select('*').eq('organization_id',p.organization_id).order('created_at',{ascending:false}),supabase.from('event_triggers').select('id,source_domain,event_type,status,idempotency_key,created_at,workflow_id,task_id').eq('organization_id',p.organization_id).order('created_at',{ascending:false}).limit(25)]);if(r.error||t.error)setError((r.error||t.error)!.message);else{setRules((r.data||[]) as Rule[]);setTriggers((t.data||[]) as Trigger[]);}setLoading(false)}
 useEffect(()=>{load()},[]);
 async function addRule(){if(!org)return;const {error:e}=await supabase.from('event_rules').insert({organization_id:org,name:'Critical monitoring signal → compliance review',source_domain:'INTELLIGENCE',event_type:'CRITICAL_SIGNAL',target_workflow_type:'COMPLIANCE',enabled:true,auto_assign_role:'COMPLIANCE',priority:'URGENT',sla_hours:4});if(e)setError(e.message);else load()}
 async function toggle(r:Rule){const {error:e}=await supabase.from('event_rules').update({enabled:!r.enabled,updated_at:new Date().toISOString()}).eq('id',r.id);if(e)setError(e.message);else load()}
 const active=rules.filter(r=>r.enabled).length, processed=triggers.filter(t=>t.status==='PROCESSED').length, failed=triggers.filter(t=>t.status==='FAILED').length;
 return <main className="mx-auto max-w-[1540px] space-y-6 p-4 md:p-8"><section className="assetflow-command rounded-3xl p-6 md:p-8"><div className="relative z-10"><div className="mb-3 flex flex-wrap items-center gap-2"><span className="assetflow-eyebrow">Phase 14 · Event Orchestration</span><span className="assetflow-status"><span className="assetflow-live-dot"/> Orchestration plane online</span></div><h1 className="font-display text-3xl font-semibold tracking-[-.04em] text-white md:text-5xl">Make institutional events executable.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-400">Rules translate upstream settlement, servicing, compliance and intelligence events into owned workflows, tasks and exceptions with deterministic idempotency.</p></div></section>
 <div className="grid grid-cols-2 gap-3 md:grid-cols-4"><K label="Active rules" value={String(active)}/><K label="Events received" value={String(triggers.length)}/><K label="Processed" value={String(processed)}/><K label="Failed" value={String(failed)}/></div>
 {error&&<div className="rounded-2xl border border-rose-400/20 bg-rose-400/5 p-4 text-sm text-rose-200">{error}</div>}
 <div className="grid gap-6 xl:grid-cols-[1.25fr_.9fr]"><Panel title="Automation rules" icon={GitBranch} action={<div className="flex gap-2"><button onClick={load} className="rounded-lg p-2 text-slate-500 hover:bg-white/5 hover:text-white"><RefreshCw className="h-4 w-4"/></button><button onClick={addRule} className="flex items-center gap-1 rounded-lg border border-cyan-400/20 px-3 py-2 text-[10px] text-cyan-300 hover:bg-cyan-400/5"><Plus className="h-3 w-3"/> Add rule</button></div>}><div className="space-y-2">{!loading&&!rules.length&&<Empty text="No event rules configured yet."/>}{rules.map(r=><div key={r.id} className="rounded-xl border border-white/[.06] bg-white/[.02] p-4"><div className="flex items-start justify-between gap-4"><div><p className="text-sm font-medium text-slate-200">{r.name}</p><p className="mt-2 font-mono text-[10px] text-cyan-300">{r.source_domain} / {r.event_type}</p><p className="mt-1 font-mono text-[10px] text-slate-600">→ {r.target_workflow_type} · {r.auto_assign_role||'UNASSIGNED'} · {r.priority} · SLA {r.sla_hours}h</p></div><button onClick={()=>toggle(r)} className={`rounded-full border px-2 py-1 text-[9px] ${r.enabled?'border-emerald-400/20 text-emerald-300':'border-white/10 text-slate-600'}`}>{r.enabled?'ENABLED':'PAUSED'}</button></div></div>)}</div></Panel>
 <Panel title="Event stream" icon={Zap}><div className="space-y-2">{!loading&&!triggers.length&&<Empty text="No orchestration events have been received."/>}{triggers.map(t=><div key={t.id} className="rounded-xl border border-white/[.06] bg-white/[.02] p-3"><div className="flex items-center justify-between"><span className="font-mono text-[9px] text-cyan-300">{t.source_domain} / {t.event_type}</span><span className={t.status==='FAILED'?'text-rose-300':'text-emerald-300'}>{t.status}</span></div><p className="mt-2 font-mono text-[9px] text-slate-600">{t.idempotency_key} · {new Date(t.created_at).toLocaleString()}</p><p className="mt-1 text-[10px] text-slate-600">{t.workflow_id?'workflow '+t.workflow_id.slice(0,8):'workflow pending'} {t.task_id?'· task '+t.task_id.slice(0,8):''}</p></div>)}</div></Panel></div>
 <Panel title="Control-plane guarantees" icon={ShieldAlert}><div className="grid gap-3 md:grid-cols-3"><Info title="Idempotent" text="Duplicate source events collapse onto one organization-scoped key."/><Info title="Auditable" text="Every received event records its rule, status and resulting work objects."/><Info title="Human accountable" text="Rules create operational work; people still own review, exception and completion decisions."/></div></Panel>
 <div className="flex items-center gap-2 text-xs text-slate-600"><Activity className="h-4 w-4"/> Phase 14 turns the Phase 13 operations control plane into an event-driven execution layer.</div></main>
}
function K({label,value}:{label:string;value:string}){return <div className="assetflow-kpi"><p>{label}</p><strong>{value}</strong><span>organization scoped</span></div>};function Info({title,text}:{title:string;text:string}){return <div className="rounded-xl border border-white/[.06] bg-white/[.02] p-4"><p className="text-sm font-medium text-white">{title}</p><p className="mt-2 text-xs leading-5 text-slate-500">{text}</p></div>};function Panel({title,icon:Icon,action,children}:{title:string;icon:any;action?:React.ReactNode;children:React.ReactNode}){return <section className="assetflow-panel rounded-2xl p-5"><div className="mb-4 flex items-center justify-between"><h2 className="flex items-center gap-2 font-display text-sm font-semibold text-white"><Icon className="h-4 w-4 text-cyan-300"/>{title}</h2>{action}</div>{children}</section>};function Empty({text}:{text:string}){return <div className="py-8 text-center text-xs text-slate-600">{text}</div>}
