'use client';

import { useEffect, useState } from 'react';
import { ShieldCheck, Users, KeyRound, Activity, UserPlus, Lock, RefreshCw } from 'lucide-react';
import { supabase } from '@/lib/supabase';

type Member = { id:string; user_id:string; role:string; status:string; last_seen_at:string|null };
type Policy = { id:string; name:string; resource:string; action:string; effect:string; role:string; enabled:boolean };
type Event = { id:string; event_type:string; resource:string|null; action:string|null; outcome:string; created_at:string };

export function Phase12AccessWorkspace() {
 const [members,setMembers]=useState<Member[]>([]); const [policies,setPolicies]=useState<Policy[]>([]); const [events,setEvents]=useState<Event[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null);
 async function load(){ setLoading(true); setError(null); const {data:{user}}=await supabase.auth.getUser(); if(!user){setError('Sign in required');setLoading(false);return;} const {data:profile}=await supabase.from('profiles').select('organization_id').eq('id',user.id).maybeSingle(); if(!profile?.organization_id){setError('No organization is assigned to this account');setLoading(false);return;} const [m,p,e]=await Promise.all([supabase.from('organization_members').select('id,user_id,role,status,last_seen_at').eq('organization_id',profile.organization_id).order('created_at',{ascending:false}),supabase.from('access_policies').select('id,name,resource,action,effect,role,enabled').eq('organization_id',profile.organization_id).order('created_at',{ascending:false}),supabase.from('access_events').select('id,event_type,resource,action,outcome,created_at').eq('organization_id',profile.organization_id).order('created_at',{ascending:false}).limit(12)]); const firstError=m.error||p.error||e.error; if(firstError)setError(firstError.message); else {setMembers((m.data||[]) as Member[]);setPolicies((p.data||[]) as Policy[]);setEvents((e.data||[]) as Event[]);} setLoading(false); }
 useEffect(()=>{load()},[]);
 const active=members.filter(m=>m.status==='ACTIVE').length, denied=events.filter(e=>e.outcome==='DENIED').length;
 return <main className="mx-auto max-w-[1540px] space-y-6 p-4 md:p-8"><section className="assetflow-command rounded-3xl p-6 md:p-8"><div className="relative z-10"><div className="mb-3 flex flex-wrap items-center gap-2"><span className="assetflow-eyebrow">Phase 12 · Institutional Access</span><span className="assetflow-status"><span className="assetflow-live-dot"/> Access control online</span></div><h1 className="font-display text-3xl font-semibold tracking-[-.04em] text-white md:text-5xl">Control who can act on institutional assets.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-400">Organization-scoped roles, policy visibility and access telemetry for operators, analysts, compliance teams and administrators.</p></div></section>
 <div className="grid grid-cols-2 gap-3 md:grid-cols-4"><K label="Active members" value={String(active)} icon={Users}/><K label="Policies" value={String(policies.length)} icon={Lock}/><K label="Access events" value={String(events.length)} icon={Activity}/><K label="Denied events" value={String(denied)} icon={ShieldCheck}/></div>
 {error&&<div className="rounded-2xl border border-rose-400/20 bg-rose-400/5 p-4 text-sm text-rose-200">{error}</div>}
 <div className="grid gap-6 lg:grid-cols-2"><Panel title="Organization members" icon={Users} action={<button onClick={load} className="rounded-lg p-2 text-slate-500 hover:bg-white/5 hover:text-white"><RefreshCw className="h-4 w-4"/></button>}><div className="space-y-2">{!loading&&!members.length&&<Empty text="No organization members yet."/>}{members.map(m=><div key={m.id} className="flex items-center justify-between rounded-xl border border-white/[.06] bg-white/[.02] p-3"><div><p className="font-mono text-xs text-slate-300">{m.user_id.slice(0,8)}…</p><p className="mt-1 text-[10px] uppercase tracking-wider text-slate-600">{m.role} · {m.status}</p></div><span className="rounded-full border border-cyan-400/20 px-2 py-1 text-[9px] text-cyan-300">{m.last_seen_at?'Seen':'Never seen'}</span></div>)}</div></Panel>
 <Panel title="Access policies" icon={KeyRound}><div className="space-y-2">{!loading&&!policies.length&&<Empty text="No custom policies configured."/>}{policies.map(p=><div key={p.id} className="rounded-xl border border-white/[.06] bg-white/[.02] p-3"><div className="flex items-center justify-between"><p className="text-sm font-medium text-slate-200">{p.name}</p><span className={p.effect==='DENY'?'text-rose-300':'text-emerald-300'}>{p.effect}</span></div><p className="mt-1 font-mono text-[10px] text-slate-600">{p.role} · {p.resource}:{p.action}</p></div>)}</div></Panel></div>
 <Panel title="Recent access telemetry" icon={Activity} action={<span className="font-mono text-[9px] text-slate-600">LAST 12 EVENTS</span>}><div className="overflow-x-auto"><table className="w-full text-left"><thead><tr className="border-b border-white/[.06] text-[9px] uppercase tracking-[.16em] text-slate-600"><th className="py-3">Event</th><th>Resource</th><th>Outcome</th><th>Time</th></tr></thead><tbody>{events.map(e=><tr key={e.id} className="border-b border-white/[.04] text-xs text-slate-400"><td className="py-3 font-mono">{e.event_type}</td><td>{e.resource||'—'} {e.action?`· ${e.action}`:''}</td><td className={e.outcome==='DENIED'?'text-rose-300':'text-emerald-300'}>{e.outcome}</td><td className="font-mono text-[10px]">{new Date(e.created_at).toLocaleString()}</td></tr>)}</tbody></table>{!loading&&!events.length&&<Empty text="No access events recorded yet."/>}</div></Panel>
 <div className="flex items-center gap-2 text-xs text-slate-600"><UserPlus className="h-4 w-4"/> Invitations and role changes can be connected to the identity provider next.</div></main>
}
function K({label,value,icon:Icon}:{label:string;value:string;icon:any}){return <div className="assetflow-kpi"><p>{label}</p><strong>{value}</strong><span><Icon className="mr-1 inline h-3 w-3"/> organization scoped</span></div>}
function Panel({title,icon:Icon,action,children}:{title:string;icon:any;action?:React.ReactNode;children:React.ReactNode}){return <section className="assetflow-panel rounded-2xl p-5"><div className="mb-4 flex items-center justify-between"><h2 className="flex items-center gap-2 font-display text-sm font-semibold text-white"><Icon className="h-4 w-4 text-cyan-300"/>{title}</h2>{action}</div>{children}</section>}
function Empty({text}:{text:string}){return <div className="py-8 text-center text-xs text-slate-600">{text}</div>}
