'use client';
import { useEffect, useState } from 'react';
import { CheckCircle2, FileCheck2, GitBranch, ShieldCheck, XCircle } from 'lucide-react';
import { supabase } from '@/lib/supabase';

type Decision={id:string;title:string;decision_type:string;status:string;created_at:string;decision_summary:string|null};
type Approval={id:string;decision_id:string;role:string|null;action:string;comment:string|null;created_at:string};
export default function DecisioningPage(){
 const [decisions,setDecisions]=useState<Decision[]>([]); const [approvals,setApprovals]=useState<Approval[]>([]); const [error,setError]=useState<string|null>(null); const [loading,setLoading]=useState(true);
 async function load(){setLoading(true);setError(null); const {data:{user}}=await supabase.auth.getUser(); if(!user){setError('Sign in required');setLoading(false);return;} const {data:p}=await supabase.from('profiles').select('organization_id').eq('id',user.id).maybeSingle(); if(!p?.organization_id){setError('No organization is assigned to this account');setLoading(false);return;} const [d,a]=await Promise.all([supabase.from('decision_requests').select('id,title,decision_type,status,created_at,decision_summary').eq('organization_id',p.organization_id).order('created_at',{ascending:false}).limit(40),supabase.from('decision_approvals').select('id,decision_id,role,action,comment,created_at').eq('organization_id',p.organization_id).order('created_at',{ascending:false}).limit(40)]); if(d.error||a.error)setError((d.error||a.error)?.message||'Unable to load decision control'); else {setDecisions(d.data||[]);setApprovals(a.data||[]);} setLoading(false);}
 useEffect(()=>{load()},[]);
 async function decide(d:Decision,action:'APPROVE'|'REJECT'|'RETURN'){const {data:{user}}=await supabase.auth.getUser(); if(!user)return; const next=action==='APPROVE'?'APPROVED':action==='REJECT'?'REJECTED':'RETURNED'; const now=new Date().toISOString(); const {error:e}=await supabase.from('decision_approvals').insert({organization_id:(await supabase.from('profiles').select('organization_id').eq('id',user.id).single()).data?.organization_id,decision_id:d.id,approver_id:user.id,action,comment:null,evidence:[]}); if(e){setError(e.message);return;} const {error:u}=await supabase.from('decision_requests').update({status:next,decided_at:now,updated_at:now}).eq('id',d.id); if(u)setError(u.message); else {await supabase.from('decision_events').insert({organization_id:(await supabase.from('profiles').select('organization_id').eq('id',user.id).single()).data?.organization_id,decision_id:d.id,actor_id:user.id,event_type:'DECISION_RECORDED',from_status:d.status,to_status:next,metadata:{action}});load();}}
 const pending=decisions.filter(d=>d.status==='PENDING').length, approved=decisions.filter(d=>d.status==='APPROVED').length, rejected=decisions.filter(d=>d.status==='REJECTED').length;
 return <main className="mx-auto max-w-[1540px] space-y-6 p-4 md:p-8"><section className="assetflow-command rounded-3xl p-6 md:p-8"><div className="relative z-10"><div className="mb-3 flex items-center gap-2"><span className="assetflow-eyebrow">Phase 15 · Institutional Decisioning</span><span className="assetflow-status"><span className="assetflow-live-dot"/> Approval control online</span></div><h1 className="font-display text-3xl font-semibold tracking-[-.04em] text-white md:text-5xl">Make institutional decisions accountable.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-400">Approval gates, segregation of duties, evidence capture and immutable decision events for high-value institutional workflows.</p></div></section>
 <div className="grid grid-cols-3 gap-3"><K l="Pending decisions" v={pending}/><K l="Approved" v={approved}/><K l="Rejected" v={rejected}/></div>{error&&<div className="rounded-2xl border border-rose-400/20 bg-rose-400/5 p-4 text-sm text-rose-200">{error}</div>}
 <div className="grid gap-6 xl:grid-cols-[1.3fr_.7fr]"><section className="assetflow-panel rounded-2xl p-5"><h2 className="mb-4 flex items-center gap-2 font-display text-sm font-semibold text-white"><ShieldCheck className="h-4 w-4 text-cyan-300"/>Decision queue</h2>{!loading&&!decisions.length&&<Empty/>}<div className="space-y-2">{decisions.map(d=><div key={d.id} className="rounded-xl border border-white/[.06] bg-white/[.02] p-4"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><div className="flex gap-2"><span className="font-mono text-[9px] text-cyan-300">{d.decision_type}</span><span className="font-mono text-[9px] text-slate-600">{d.status}</span></div><p className="mt-2 text-sm font-medium text-slate-200">{d.title}</p><p className="mt-1 text-[10px] text-slate-600">{d.decision_summary||'Evidence review required'} · {new Date(d.created_at).toLocaleString()}</p></div>{d.status==='PENDING'&&<div className="flex gap-2"><button onClick={()=>decide(d,'RETURN')} className="rounded-lg border border-white/10 px-3 py-2 text-[9px] text-slate-300">Return</button><button onClick={()=>decide(d,'REJECT')} className="rounded-lg border border-rose-400/20 px-3 py-2 text-[9px] text-rose-300">Reject</button><button onClick={()=>decide(d,'APPROVE')} className="rounded-lg border border-emerald-400/20 px-3 py-2 text-[9px] text-emerald-300">Approve</button></div>}</div></div>)}</div></section>
 <section className="assetflow-panel rounded-2xl p-5"><h2 className="mb-4 flex items-center gap-2 font-display text-sm font-semibold text-white"><GitBranch className="h-4 w-4 text-cyan-300"/>Decision trail</h2>{!approvals.length&&<Empty/>}<div className="space-y-2">{approvals.map(a=><div key={a.id} className="rounded-xl border border-white/[.06] p-3"><div className="flex justify-between"><span className="font-mono text-[9px] text-slate-500">{a.role||'APPROVER'}</span><span className="font-mono text-[9px] text-cyan-300">{a.action}</span></div><p className="mt-2 text-[10px] text-slate-500">{a.comment||'No comment recorded'} · {new Date(a.created_at).toLocaleString()}</p></div>)}</div></section></div>
 <div className="flex items-center gap-2 text-xs text-slate-600"><FileCheck2 className="h-4 w-4"/> Every approval is paired with an approval record and decision event.</div></main>}
function K({l,v}:{l:string;v:number}){return <div className="assetflow-kpi"><p>{l}</p><strong>{v}</strong><span>organization scoped</span></div>} function Empty(){return <div className="py-8 text-center text-xs text-slate-600">No decision records yet.</div>}
